### ISSUE TITLE
Any chance of getting this updated to Sponge 7?

### ISSUE THREAD

**Issue by funnykeyboardsymbols** [lucko/tapir#6]
I would love some kind of scripting engine for Sponge and this seems like the best (only?) option.

**Comment by oblx** [comment]
I am currently having fun with `tapir` and `spongevanilla-1.12.2-7.3.0` and there is only a warning at server startup : 

``[Sponge]: Plugin tapir from mods\tapir.jar was designed for spongeapi 6.0.0. It may not work properly.``

Scripts are included through nashorn `load()` instead of `loader.watch()` and everything works fine. Let's have a talk if you start scripting :)

**Comment by lucko** [comment]
It should still work for API7!

**Comment by funnykeyboardsymbols** [comment]
Thanks!
